#!/usr/bin/env bash
set -e
PLUGINS="cpp csharp dart go java js kotlin objc php pyi python ruby"
PROTOS="proto2 proto3 proto2023"

rm -fr gen
rm -fr errors

(
    echo "<!-- AUTOGENERATED BY ./shootout.sh -->"
    echo "# Protobuf Version Support"
    echo "Not all protobuf plugins support all versions of Protobuf."
    echo "This test suite provides information about what versions of protobuf"
    echo "work with which protoc plugins."
    echo ""
    echo "## Versions"
    echo "- **protoc**: \`$(protoc --version)\`"
    echo "- **protoc-gen-go**: \`$(protoc-gen-go --version)\`"
    echo ""
    echo "## Support Matrix"
    echo -n "| |"
    for proto in $PROTOS; do
        echo -n " $proto |"
    done
    echo ""
    echo -n "| --- |"
    for proto in $PROTOS; do
        echo -n " --- |"
    done
    echo ""
    for plugin in $PLUGINS; do
        echo -n "| $plugin | "
        for proto in $PROTOS; do
            out="./gen/$proto/$plugin"
            mkdir -p "$out"
            if protoc "--${plugin}_out=$out" "proto/${proto}/test_$proto.proto" >./protoc.log 2>&1; then
                echo -n " :white_check_mark: |"
                rm protoc.log
            else
                mkdir -p errors
                logfile="./errors/${plugin}-${proto}.log"
                mv protoc.log "$logfile"
                echo -n " [:x:]($logfile) |"
            fi
        done
        echo ""
    done
)> README.md
